"""MoGenTS spatial-temporal decoding helpers.

MoGenTS uses two token streams:

1. a 1D auxiliary stream over time, generated by ``MaskTransformer`` and
   ``ResidualTransformer``;
2. a 2D spatial-temporal stream over ``T x 6`` joint groups, generated by
   ``MaskTransformer2D`` and ``ResidualTransformer2D``.

Both streams are decoded together by the MoGenTS RVQ-VAE. The returned motion is
still in the RVQ-VAE normalized HumanML3D feature space; callers denormalize
with the checkpoint ``Mean`` / ``Std``.
"""

from __future__ import annotations

from typing import Sequence

import torch
import torch.nn.functional as F
from torch.distributions.categorical import Categorical


@torch.no_grad()
def estimate_token_lengths(
    text_transformer,
    length_estimator,
    captions: Sequence[str],
) -> torch.Tensor:
    """Sample per-caption token lengths from the frozen CLIP text feature."""
    text_embedding = text_transformer.encode_text(list(captions))
    pred_dis = length_estimator(text_embedding)
    probs = F.softmax(pred_dis, dim=-1)
    return Categorical(probs).sample().long()


@torch.no_grad()
def generate_motion(
    mask_transformer_aux,
    mask_transformer_ts,
    res_transformer_aux,
    res_transformer_ts,
    vq_model,
    captions: Sequence[str],
    token_lens: torch.Tensor,
    *,
    cond_scale: float = 4.0,
    time_steps: int = 10,
    temperature: float = 1.0,
    topk_filter_thres: float = 0.9,
    gsample: bool = False,
    res_cond_scale: float = 5.0,
    res_temperature: float = 1.0,
    n_joint_groups: int = 6,
) -> torch.Tensor:
    """Run the full MoGenTS T2M decoding stack.

    Args:
        mask_transformer_aux: 1D auxiliary base-token transformer.
        mask_transformer_ts: 2D spatial-temporal base-token transformer.
        res_transformer_aux: 1D residual transformer.
        res_transformer_ts: 2D residual transformer.
        vq_model: dual-stream MoGenTS RVQ-VAE.
        captions: list of B text prompts.
        token_lens: ``(B,)`` LongTensor of token counts (= frames // 4).

    Returns:
        ``(B, T, 263)`` normalized HumanML3D motion, where
        ``T = max(token_lens) * 4``.
    """
    captions = list(captions)
    mids_aux = mask_transformer_aux.generate(
        captions,
        token_lens,
        timesteps=time_steps,
        cond_scale=cond_scale,
        temperature=temperature,
        topk_filter_thres=topk_filter_thres,
        gsample=gsample,
    )
    mids_ts = mask_transformer_ts.generate(
        captions,
        token_lens,
        timesteps=time_steps,
        cond_scale=cond_scale,
        temperature=temperature,
        topk_filter_thres=topk_filter_thres,
        gsample=gsample,
        n_j=n_joint_groups,
    )
    mids_aux = res_transformer_aux.generate(
        mids_aux,
        captions,
        token_lens,
        temperature=res_temperature,
        cond_scale=res_cond_scale,
    )
    mids_ts = res_transformer_ts.generate(
        mids_ts,
        captions,
        token_lens,
        temperature=res_temperature,
        cond_scale=res_cond_scale,
    )
    _, pred_motions = vq_model.forward_decoder(mids_aux, mids_ts)
    return pred_motions
